#!/bin/sh

. /lib/lsb/init-functions
DAEMON=/home/user/bin/the-service
PIDFILE=/var/run/the-service.pid
OPTS="-Dcustom.opt=value"

case "$1" in
  start)
    start-stop-daemon --start --quiet --oknodo -b -m -p $PIDFILE -c user --exec $DAEMON -- $OPTS
    ;;
  stop)
    start-stop-daemon --stop --quiet --oknodo -p $PIDFILE
    ;;
  restart)
    $0 stop && sleep 3 && $0 start
    ;;
status)
    status_of_proc $DAEMON "Service Name"
    ;;
  *)
    echo "Usage: $N {start|stop|restart|status}" >&2
    exit 1
    ;;
esac

exit 0

